version: '3'
services:
  backend:
    container_name: exzi_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: "${NODE_ENV}"
    ports:
      - "${PORT}:${PORT}" # App port
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - redis
    networks:
      - exzi-network

  redis:
    container_name: exzi_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - exzi-network


networks:
  exzi-network:
    driver: bridge
